import type { Metadata } from "next";
import { Geist, Geist_Mono,Playfair_Display,Inter,Space_Grotesk} from "next/font/google";
import { ClerkProvider} from '@clerk/nextjs'
import "./globals.css";
import Header from "../components/Header"; 
import Footer from "../components/Footer"
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  subsets:["latin"],
  display:"swap",
  variable:"--font-space",
})

const inter = Inter({
  subsets:['latin'],
  variable:'--font-inter',
  display:'swap'
})

const geist = Geist({subsets:['latin'],variable:'--font-sans'})

const playfair = Playfair_Display({
  subsets:["latin"],
  variable:"--font-playfair"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, playfair.variable, spaceGrotesk.variable, "font-sans", geist.variable, inter.variable)}
    >
      <body className="min-h-full flex flex-col">
       <ClerkProvider>
          <Header />
          <TooltipProvider>
            {children}
          </TooltipProvider>
          <Footer/>
       </ClerkProvider>
        
      </body>
    </html>
  );
}
